In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("cleaned_online_retail.xlsx")

# Exploratory Data Analysis (EDA)

# Dataset Understanding

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34

In [4]:
df.shape

(210716, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210716 entries, 0 to 210715
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    210716 non-null  int64
 1   StockCode    210716 non-null  object
 2   Description  210716 non-null  object
 3   Quantity     210716 non-null  int64
 4   InvoiceDate  210716 non-null  datetime64[ns]
 5   UnitPrice    210716 non-null  float64
 6   CustomerID   210716 non-null  int64
 7   Country      210716 non-null  object
 8   Revenue      210716 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(3)
memory usage: 14.5+ MB

In [6]:
df.describe()

,InvoiceNo,Quantity,InvoiceDate,UnitPrice,CustomerID,Revenue
count,210716.000000,210716.000000,210716,210716.000000,210716.000000,210716.000000
mean,549983.103542,13.580298,2011-04-18 02:02:38.017805824,3.216361,15286.411972,23.190448
min,536365.000000,1.000000,2010-01-12 08:26:00,0.000000,12346.000000,0.000000
25%,543452.000000,2.000000,2011-02-16 11:45:00,1.250000,13867.000000,5.040000
50%,549964.000000,6.000000,2011-04-28 13:35:00,1.950000,15150.000000,12.700000
75%,556733.000000,12.000000,2011-07-07 13:02:00,3.750000,16839.000000,19.800000
max,563189.000000,74215.000000,2011-12-08 15:22:00,8142.750000,18287.000000,77183.600000
std,7759.578607,168.080725,NaN,22.540538,1729.855358,202.787266

In [7]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
Revenue        0
dtype: int64