##Import Required Libraries

In [1]:
import pandas as pd

## Load Project Files

In [2]:
kpi = pd.read_excel("Business_KPI_Dashboard.xlsx")

decision = pd.read_excel(
    "Business_Decision_Recommendations.xlsx",
    sheet_name="Decision Report"
)

print("Project files loaded successfully.")

display(kpi)

Project files loaded successfully.

,RegionSegment,Total_Customers,Total_Orders,Total_Revenue,Average_Order_Value,Purchase_Frequency,Historical_CLTV,Revenue_Rank,CLTV_Rank
0,Europe,186,615,462471.320,751.99,3.31,2489.09,3,2
1,Other,128,425,464744.970,1093.52,3.32,3630.49,2,1
2,UK,2908,9623,3959382.112,411.45,3.31,1361.90,1,3

## Project Overview

In [4]:
overview = pd.DataFrame({
    "Project Information":[
        "Project Title",
        "Dataset",
        "Duration",
        "Objective"
    ],
    "Details":[
        "Cohort Retention Analysis and Customer Lifetime Value (CLTV) Analysis",
        "Online Retail E-Commerce Dataset",
        "4 Weeks",
        "Analyze customer retention, evaluate CLTV, and generate strategic business insights."
    ]
})
print("="*60)
print("PROJECT OVERVIEW")
print("="*60)
display(overview)

============================================================
PROJECT OVERVIEW
============================================================

  Project Information                                            Details
0       Project Title  Cohort Retention Analysis and Customer Lifetim...
1             Dataset                   Online Retail E-Commerce Dataset
2            Duration                                            4 Weeks
3           Objective  Analyze customer retention, evaluate CLTV, and...

##Week-wise Project Summary

In [5]:
week_summary = pd.DataFrame({

    "Week":[
        "Week 1",
        "Week 2",
        "Week 3",
        "Week 4"
    ],
    "Major Work Completed":[
        "Performed data cleaning, preprocessing, and exploratory data analysis.",
        "Built Cohort Retention Matrix and calculated customer retention rates.",
        "Calculated Historical CLTV, AOV, Purchase Frequency, and analyzed customer segments.",
        "Developed KPI Dashboard, Executive Business Insights, Regional Performance Analysis, and Business Decision Engine."
    ]

})

print("="*60)
print("WEEK-WISE PROJECT SUMMARY")
print("="*60)

display(week_summary)

============================================================
WEEK-WISE PROJECT SUMMARY
============================================================

     Week                               Major Work Completed
0  Week 1  Performed data cleaning, preprocessing, and ex...
1  Week 2  Built Cohort Retention Matrix and calculated c...
2  Week 3  Calculated Historical CLTV, AOV, Purchase Freq...
3  Week 4  Developed KPI Dashboard, Executive Business In...

## Final Business KPI Summary

In [15]:

kpi_summary = pd.DataFrame({

    "Business KPI":[

        "Highest Revenue Region",

        "Highest Historical CLTV Region",

        "Highest Purchase Frequency Region",

        "Highest Average Order Value Region",

        "Highest Customer Count"

    ],

    "Best Performing Region":[

        kpi.loc[kpi["Revenue_Rank"]==1,"RegionSegment"].values[0],

        kpi.loc[kpi["CLTV_Rank"]==1,"RegionSegment"].values[0],

        kpi.loc[kpi["Purchase_Frequency"].idxmax(),"RegionSegment"],

        kpi.loc[kpi["Average_Order_Value"].idxmax(),"RegionSegment"],

        kpi.loc[kpi["Total_Customers"].idxmax(),"RegionSegment"]

    ],

    "Value":[

        kpi.loc[kpi["Revenue_Rank"]==1,"Total_Revenue"].values[0],

        kpi.loc[kpi["CLTV_Rank"]==1,"Historical_CLTV"].values[0],

        kpi.loc[kpi["Purchase_Frequency"].idxmax(),"Purchase_Frequency"],

        kpi.loc[kpi["Average_Order_Value"].idxmax(),"Average_Order_Value"],

        kpi.loc[kpi["Total_Customers"].idxmax(),"Total_Customers"]

    ]

})

print("="*60)
print("FINAL BUSINESS KPI SUMMARY")
print("="*60)

display(kpi_summary)

============================================================
FINAL BUSINESS KPI SUMMARY
============================================================

                         Business KPI Best Performing Region        Value
0              Highest Revenue Region                     UK  3959382.112
1      Highest Historical CLTV Region                  Other     3630.490
2   Highest Purchase Frequency Region                  Other        3.320
3  Highest Average Order Value Region                  Other     1093.520
4              Highest Customer Count                     UK     2908.000

##Project Deliverables & Outcomes

In [7]:
deliverables = pd.DataFrame({
    "Deliverable":[
        "Data Cleaning & Preprocessing",
        "Cohort Retention Analysis",
        "Historical CLTV Analysis",
        "Business KPI Dashboard",
        "Executive Business Insights",
        "Regional Performance Analysis",
        "Business Decision Engine"
    ],
    "Outcome":[
        "Successfully cleaned missing values, removed cancelled transactions and prepared the dataset.",
        "Generated cohort retention matrix to analyze customer retention over time.",
        "Calculated Historical CLTV, AOV and Purchase Frequency for customer segments.",
        "Developed a KPI dashboard summarizing customer performance metrics.",
        "Generated business insights to support data-driven decision making.",
        "Compared regional customer performance and identified strengths and weaknesses.",
        "Implemented a rule-based decision engine to generate strategic business recommendations."
    ]
})
print("="*60)
print("PROJECT DELIVERABLES")
print("="*60)

display(deliverables)

============================================================
PROJECT DELIVERABLES
============================================================

,Deliverable,Outcome
0,Data Cleaning & Preprocessing,"Successfully cleaned missing values, removed c..."
1,Cohort Retention Analysis,Generated cohort retention matrix to analyze c...
2,Historical CLTV Analysis,"Calculated Historical CLTV, AOV and Purchase F..."
3,Business KPI Dashboard,Developed a KPI dashboard summarizing customer...
4,Executive Business Insights,Generated business insights to support data-dr...
5,Regional Performance Analysis,Compared regional customer performance and ide...
6,Business Decision Engine,Implemented a rule-based decision engine to ge...

##Key Business Findings

In [8]:
findings = pd.DataFrame({
    "Business Finding":[
        "Highest Revenue Region",
        "Highest Historical CLTV Region",
        "Highest Purchase Frequency Region",
        "Decision Engine Result",
        "Overall Business Outcome"
    ],
    "Observation":[
        kpi.loc[kpi["Revenue_Rank"]==1,"RegionSegment"].values[0],
        kpi.loc[kpi["CLTV_Rank"]==1,"RegionSegment"].values[0],
        kpi.loc[kpi["Purchase_Frequency"].idxmax(),"RegionSegment"],

        "Generated automated recommendations for each customer segment.",

        "Project successfully transformed business data into actionable insights."

    ]

})

print("="*60)
print("KEY BUSINESS FINDINGS")
print("="*60)

display(findings)

============================================================
KEY BUSINESS FINDINGS
============================================================

,Business Finding,Observation
0,Highest Revenue Region,UK
1,Highest Historical CLTV Region,Other
2,Highest Purchase Frequency Region,Other
3,Decision Engine Result,Generated automated recommendations for each c...
4,Overall Business Outcome,Project successfully transformed business data...

##Final Strategic Recommendations

In [16]:
recommendations = pd.DataFrame({

    "Recommendation":[
        "Strengthen customer retention programs in high-revenue regions.",
        "Increase marketing investment in high-CLTV customer segments.",
        "Launch promotional campaigns in low-performing regions.",
        "Monitor customer KPIs regularly to improve business performance.",
        "Use rule-based recommendations to support business decisions."
    ],
    "Priority":[
        "High",
        "High",
        "Medium",
        "High",
        "Medium"
    ],

    "Expected Business Impact":[
        "Improve customer loyalty and repeat purchases.",
        "Acquire more high-value customers.",
        "Increase regional revenue.",
        "Support continuous business improvement.",
        "Enable data-driven strategic planning."

    ]

})

print("="*60)
print("FINAL STRATEGIC RECOMMENDATIONS")
print("="*60)

display(recommendations)

============================================================
FINAL STRATEGIC RECOMMENDATIONS
============================================================

,Recommendation,Priority,Expected Business Impact
0,Strengthen customer retention programs in high...,High,Improve customer loyalty and repeat purchases.
1,Increase marketing investment in high-CLTV cus...,High,Acquire more high-value customers.
2,Launch promotional campaigns in low-performing...,Medium,Increase regional revenue.
3,Monitor customer KPIs regularly to improve bus...,High,Support continuous business improvement.
4,Use rule-based recommendations to support busi...,Medium,Enable data-driven strategic planning.

##Final Project Conclusion

In [13]:
print("="*60)
print("FINAL PROJECT CONCLUSION")
print("="*60)

print("""

This project successfully analyzed customer retention,
evaluated Historical Customer Lifetime Value (CLTV),
identified high-value customer segments,
developed business KPI dashboards,
generated executive business insights,
performed regional performance analysis,
and implemented a rule-based business decision engine.

The project provides valuable business intelligence that
supports customer retention, revenue optimization,
customer segmentation, and strategic decision-making.

""")

============================================================
FINAL PROJECT CONCLUSION
============================================================


This project successfully analyzed customer retention,
evaluated Historical Customer Lifetime Value (CLTV),
identified high-value customer segments,
developed business KPI dashboards,
generated executive business insights,
performed regional performance analysis,
and implemented a rule-based business decision engine.

The project provides valuable business intelligence that
supports customer retention, revenue optimization,
customer segmentation, and strategic decision-making.

##Save Final Project Summary

In [17]:


with pd.ExcelWriter("Final_Project_Summary.xlsx") as writer:

    overview.to_excel(
        writer,
        sheet_name="Project Overview",
        index=False
    )

    week_summary.to_excel(
        writer,
        sheet_name="Week Summary",
        index=False
    )

    kpi_summary.to_excel(
        writer,
        sheet_name="Business KPIs",
        index=False
    )

    deliverables.to_excel(
        writer,
        sheet_name="Project Deliverables",
        index=False
    )

    findings.to_excel(
        writer,
        sheet_name="Key Findings",
        index=False
    )

    recommendations.to_excel(
        writer,
        sheet_name="Recommendations",
        index=False
    )

print("Final_Project_Summary.xlsx saved successfully.")

Final_Project_Summary.xlsx saved successfully.