# CUSTOMER SEGMENTATION

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("Cohort_readydataset.xlsx")

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,CohortMonth,InvoiceMonth
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850,United Kingdom,15.30,2010-01,2010-01
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34,2010-01,2010-01
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850,United Kingdom,22.00,2010-01,2010-01
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34,2010-01,2010-01
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34,2010-01,2010-01

In [5]:
df.shape

(210716, 11)

In [6]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'CohortMonth',
       'InvoiceMonth'],
      dtype='object')

# CREATE REGION SEGMENTS

In [7]:
sorted(df['Country'].unique())

['Australia',
 'Austria',
 'Bahrain',
 'Belgium',
 'Brazil',
 'Canada',
 'Channel Islands',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'EIRE',
 'European Community',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Lebanon',
 'Lithuania',
 'Malta',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'Saudi Arabia',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'USA',
 'United Arab Emirates',
 'United Kingdom',
 'Unspecified']

In [8]:
def region_segment(country):
    if country == "United Kingdom":
        return "UK"
    elif country in ["France", "Germany", "Spain", "Belgium", "Netherlands"]:
        return "Europe"
    else:
        return "Other"
df["RegionSegment"] = df["Country"].apply(region_segment)

In [9]:
df[['Country', 'RegionSegment']].head(10)

          Country RegionSegment
0  United Kingdom            UK
1  United Kingdom            UK
2  United Kingdom            UK
3  United Kingdom            UK
4  United Kingdom            UK
5  United Kingdom            UK
6  United Kingdom            UK
7  United Kingdom            UK
8  United Kingdom            UK
9  United Kingdom            UK

In [10]:
df['RegionSegment'].value_counts()

RegionSegment
UK        186802
Europe     13181
Other      10733
Name: count, dtype: int64

# GROUP CUSTOMER INTO SEGMENTS

In [11]:
df.groupby('RegionSegment')['CustomerID'].nunique()

RegionSegment
Europe     186
Other      128
UK        2908
Name: CustomerID, dtype: int64

In [12]:
df.groupby('RegionSegment').size()

RegionSegment
Europe     13181
Other      10733
UK        186802
dtype: int64

In [13]:
df.shape

(210716, 12)

# DATA VALIDATION CHECKS

In [15]:
df.isnull().sum()

InvoiceNo        0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
UnitPrice        0
CustomerID       0
Country          0
Revenue          0
CohortMonth      0
InvoiceMonth     0
RegionSegment    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(2285)

In [17]:
df.shape

(210716, 12)

In [18]:
df.dtypes

InvoiceNo                 int64
StockCode                object
Description              object
Quantity                  int64
InvoiceDate      datetime64[ns]
UnitPrice               float64
CustomerID                int64
Country                  object
Revenue                 float64
CohortMonth              object
InvoiceMonth             object
RegionSegment            object
dtype: object