# Week 3 - Segment-wise Customer Behaviour Analysis

## Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use("default")

# Load Segmented Dataset

In [2]:
df = pd.read_excel("Segmented_cohortdataset.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,CohortMonth,InvoiceMonth,RegionSegment
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-01-12 08:26:00,2.55,17850,United Kingdom,15.30,2010-01,2010-01,UK
1,536365,71053,WHITE METAL LANTERN,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34,2010-01,2010-01,UK
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-01-12 08:26:00,2.75,17850,United Kingdom,22.00,2010-01,2010-01,UK
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34,2010-01,2010-01,UK
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-01-12 08:26:00,3.39,17850,United Kingdom,20.34,2010-01,2010-01,UK

# Dataset Overview

In [3]:
print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (210716, 12)

Columns:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country', 'Revenue', 'CohortMonth', 'InvoiceMonth', 'RegionSegment']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210716 entries, 0 to 210715
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceNo      210716 non-null  int64
 1   StockCode      210716 non-null  object
 2   Description    210716 non-null  object
 3   Quantity       210716 non-null  int64
 4   InvoiceDate    210716 non-null  datetime64[ns]
 5   UnitPrice      210716 non-null  float64
 6   CustomerID     210716 non-null  int64
 7   Country        210716 non-null  object
 8   Revenue        210716 non-null  float64
 9   CohortMonth    210716 non-null  object
 10  InvoiceMonth   210716 non-null  object
 11  RegionSegment  210716 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(6)
memory usage: 19.3+ MB

In [5]:
df.isnull().sum()

InvoiceNo        0
StockCode        0
Description      0
Quantity         0
InvoiceDate      0
UnitPrice        0
CustomerID       0
Country          0
Revenue          0
CohortMonth      0
InvoiceMonth     0
RegionSegment    0
dtype: int64

# Business Metrics Calculation

## Create Revenue Column (if not already present)

In [6]:
if "Revenue" not in df.columns:
    df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print("Revenue column is ready.")

df[["Quantity", "UnitPrice", "Revenue"]].head()

Revenue column is ready.

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

## Calculate Business Metrics by Region

In [7]:
summary = df.groupby("RegionSegment").agg(
    Total_Revenue=("Revenue", "sum"),
    Total_Orders=("InvoiceNo", "nunique"),
    Total_Customers=("CustomerID", "nunique")
).reset_index()

summary

  RegionSegment  Total_Revenue  Total_Orders  Total_Customers
0        Europe     462471.320           615              186
1         Other     464744.970           425              128
2            UK    3959382.112          9623             2908

## Calculate Average Order Value (AOV)

In [8]:
summary["Average_Order_Value"] = (
    summary["Total_Revenue"] /
    summary["Total_Orders"]
)

summary[["RegionSegment", "Average_Order_Value"]]

  RegionSegment  Average_Order_Value
0        Europe           751.985886
1         Other          1093.517576
2            UK           411.449871

## Calculate Purchase Frequency

In [9]:
summary["Purchase_Frequency"] = (
    summary["Total_Orders"] /
    summary["Total_Customers"]
)

summary["Average_Order_Value"] = summary["Average_Order_Value"].round(2)
summary["Purchase_Frequency"] = summary["Purchase_Frequency"].round(2)

summary

,RegionSegment,Total_Revenue,Total_Orders,Total_Customers,Average_Order_Value,Purchase_Frequency
0,Europe,462471.320,615,186,751.99,3.31
1,Other,464744.970,425,128,1093.52,3.32
2,UK,3959382.112,9623,2908,411.45,3.31